// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzgcbgfskdqbqniclyha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Z2NiZ2Zza2RxYnFuaWNseWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjQ1NTIsImV4cCI6MjA1ODY0MDU1Mn0.CH7osiF8Ax7FfhG6si9FTYQSIsBbo7icJvp-aQB-3qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);